server:
  port: 9092
  servlet:
    context-path: /dept-api

spring:
  boot:
    message: Hello Department Service
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      
logging:
  level:
    com:
      geetesh:
        department:
          service: debug

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
