server:
  port: 9092
  servlet:
    context-path: /dept-api

spring:
  boot:
    message: Hi Boss Baby
#   config:
#     import: "configserver:http://localhost:9090"
#  h2:
#    console:
#      enabled: true
  # application:
  #   name: DEPARTMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: admin
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    com:
      geetesh:
        department:
          service: debug

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
