server:
  port: 9094
  servlet:
    context-path: /org-api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/organization_db
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  boot:
    message: Hello Organization Service Updated
      
logging:
  level:
    com:
      geetesh:
        organization:
          service: debug

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
