
server:
  port: 9093
  servlet:
    context-path: /user-api

spring:
  boot:
    message: Hello user
  # config:
  #   import: "configserver:http://localhost:9090"
  # h2:
  #   console:
  #     enabled: true
  # application:
  #   name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: admin
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

department:
  service:
    url: http://DEPARTMENT-SERVICE/dept-api/departments/

logging:
  level:
    com:
      geetesh:
        user:
          service: debug
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include:
          - "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
    env:
      show-values: ALWAYS
info:
  app:
    name: User Service
    description: Spring boot application for User Service
    version: 1.0.0
