
server:
  port: 9093
  servlet:
    context-path: /user-api

spring:
  boot:
    message: Hello User Service Updated
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

department:
  service:
    url: http://DEPARTMENT-SERVICE/dept-api/departments/

logging:
  level:
    com:
      geetesh:
        user:
          service: debug
          
management:
  tracing:
    sampling:
      probability: 1.0   #To publish all the traces(100%) to Micrometer so that same would be visible in Zipkin
  endpoints:
    web:
      exposure:
        include:
          - "*"   # To expose all the actuator endpoints
  health:
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS #To show the details
    env:
      show-values: ALWAYS

info:  # Application details which would be show in actuator/info endpoint
  app:
    name: User Service
    description: Spring boot application for User Service
    version: 1.0.0   
    
#Circuit Breaker properties
resilience4j:
  circuitbreaker:
    instances:
      USER-SERVICE:
        registerHealthIndicator: true
        failureRateThreshold: 60
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 50
